### ISSUE TITLE
Error in Main

### ISSUE THREAD

**Issue by willnes** [lovelytt0/GMPE_BP#1]
Thank you for sharing the code
When I run Main and click the readteleBp button, an error occurs, prompting: 
Undefined function or variable'readAllSac'. 
Error readteleBP (line 12); opr=readAllSac()
Can you provide the readAllSac function?
Many thanks

**Comment by lovelytt0** [comment]
Here is the https://github.com/lovelytt0/GMPE_BP/blob/master/lib/readAllSac.m,  it might be path issue of matlab. Hope this answer is not too late
